let data = [
  {
    planet: "Mercury",
    description: "Mercury is the smallest planet in the Solar System and the closest to the Sun. It has a very thin atmosphere and extreme temperature variations.",
    diameter: "4879 km",
    mass: "3.30 x 10^23 kg",
    gravity: "3.7 m/s²",
    orbitalPeriod: "88 days",
    rotationPeriod: "59 days",
    distanceFromSun: "57.9 million km",
    numberOfMoons: 0,
    surfaceTemperature: "-173°C to 427°C",
    atmosphereComposition: "Oxygen, Sodium, Hydrogen, Helium",
    interestingFacts: "Mercury has no moons and experiences the most extreme temperature changes in the Solar System."
  },
  {
    planet: "Venus",
    description: "Venus is the second planet from the Sun and is often called Earth's sister planet due to their similar size. It has a thick, toxic atmosphere that traps heat, making it the hottest planet.",
    diameter: "12104 km",
    mass: "4.87 x 10^24 kg",
    gravity: "8.87 m/s²",
    orbitalPeriod: "225 days",
    rotationPeriod: "243 days (retrograde)",
    distanceFromSun: "108.2 million km",
    numberOfMoons: 0,
    surfaceTemperature: "465°C",
    atmosphereComposition: "96% Carbon Dioxide, 3% Nitrogen",
    interestingFacts: "Venus has a day longer than its year and rotates in the opposite direction to most planets."
  },
  {
    planet: "Earth",
    description: "Earth is the third planet from the Sun and the only known planet to support life. It is an ocean world, with 71% of its surface covered in water.",
    diameter: "12742 km",
    mass: "5.97 x 10^24 kg",
    gravity: "9.8 m/s²",
    orbitalPeriod: "365.25 days",
    rotationPeriod: "24 hours",
    distanceFromSun: "149.6 million km",
    numberOfMoons: 1,
    surfaceTemperature: "14°C (average)",
    atmosphereComposition: "78% Nitrogen, 21% Oxygen, 1% Other Gases",
    interestingFacts: "Earth is the densest planet in the Solar System and the only one with liquid water on its surface."
  },
  {
    planet: "Mars",
    description: "Mars is the fourth planet from the Sun and is known as the Red Planet due to its reddish appearance. It has the largest volcano and canyon in the Solar System.",
    diameter: "6779 km",
    mass: "6.42 x 10^23 kg",
    gravity: "3.71 m/s²",
    orbitalPeriod: "687 days",
    rotationPeriod: "24.6 hours",
    distanceFromSun: "227.9 million km",
    numberOfMoons: 2,
    surfaceTemperature: "-63°C (average)",
    atmosphereComposition: "95% Carbon Dioxide, 3% Nitrogen, 1.6% Argon",
    interestingFacts: "Mars has seasons like Earth, but they last about twice as long."
  },
  {
    planet: "Jupiter",
    description: "Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant known for its Great Red Spot, a giant storm that has lasted for centuries.",
    diameter: "139820 km",
    mass: "1.90 x 10^27 kg",
    gravity: "24.79 m/s²",
    orbitalPeriod: "11.86 years",
    rotationPeriod: "9.9 hours",
    distanceFromSun: "778.5 million km",
    numberOfMoons: 79,
    surfaceTemperature: "-108°C",
    atmosphereComposition: "90% Hydrogen, 10% Helium",
    interestingFacts: "Jupiter has the strongest magnetic field of any planet and over 75 moons, including Ganymede, the largest moon in the Solar System."
  },
  {
    planet: "Saturn",
    description: "Saturn is the sixth planet from the Sun and is famous for its stunning ring system. It is a gas giant like Jupiter and has a low density, being able to float in water.",
    diameter: "116460 km",
    mass: "5.68 x 10^26 kg",
    gravity: "10.44 m/s²",
    orbitalPeriod: "29.5 years",
    rotationPeriod: "10.7 hours",
    distanceFromSun: "1.43 billion km",
    numberOfMoons: 83,
    surfaceTemperature: "-139°C",
    atmosphereComposition: "96% Hydrogen, 4% Helium",
    interestingFacts: "Saturn's rings are made mostly of ice and rock and are only about 20 meters thick."
  },
  {
    planet: "Uranus",
    description: "Uranus is the seventh planet from the Sun and has a unique tilt, rotating on its side. It is an ice giant with a blue-green color due to methane in its atmosphere.",
    diameter: "50724 km",
    mass: "8.68 x 10^25 kg",
    gravity: "8.69 m/s²",
    orbitalPeriod: "84 years",
    rotationPeriod: "17.2 hours",
    distanceFromSun: "2.87 billion km",
    numberOfMoons: 27,
    surfaceTemperature: "-195°C",
    atmosphereComposition: "82% Hydrogen, 15% Helium, 2% Methane",
    interestingFacts: "Uranus has faint rings and its axis is tilted at an angle of 98 degrees, making it roll around the Sun on its side."
  },
  {
    planet: "Neptune",
    description: "Neptune is the eighth and farthest known planet from the Sun in the Solar System. It is an ice giant known for its deep blue color and supersonic winds.",
    diameter: "49244 km",
    mass: "1.02 x 10^26 kg",
    gravity: "11.15 m/s²",
    orbitalPeriod: "165 years",
    rotationPeriod: "16.1 hours",
    distanceFromSun: "4.50 billion km",
    numberOfMoons: 14,
    surfaceTemperature: "-201°C",
    atmosphereComposition: "80% Hydrogen, 19% Helium, 1% Methane",
    interestingFacts: "Neptune has the strongest winds in the Solar System, reaching speeds of up to 2,100 km/h."
  }
];
