let data = [
  {
    planet: "Mercúrio",
    description: "Mercúrio é o menor planeta do Sistema Solar e o mais próximo do Sol. Ele tem uma atmosfera muito fina e variações extremas de temperatura.",
    diameter: "4879 km",
    mass: "3,30 x 10^23 kg",
    gravity: "3,7 m/s²",
    orbitalPeriod: "88 dias",
    rotationPeriod: "59 dias",
    distanceFromSun: "57,9 milhões de km",
    numberOfMoons: 0,
    surfaceTemperature: "-173°C a 427°C",
    atmosphereComposition: "Oxigênio, Sódio, Hidrogênio, Hélio",
    interestingFacts: "Mercúrio não tem luas e experimenta as mudanças de temperatura mais extremas do Sistema Solar."
  },
  {
    planet: "Vênus",
    description: "Vênus é o segundo planeta a partir do Sol e muitas vezes é chamado de planeta irmão da Terra devido ao seu tamanho semelhante. Ele tem uma atmosfera espessa e tóxica que retém calor, tornando-o o planeta mais quente.",
    diameter: "12104 km",
    mass: "4,87 x 10^24 kg",
    gravity: "8,87 m/s²",
    orbitalPeriod: "225 dias",
    rotationPeriod: "243 dias (retrógrado)",
    distanceFromSun: "108,2 milhões de km",
    numberOfMoons: 0,
    surfaceTemperature: "465°C",
    atmosphereComposition: "96% Dióxido de Carbono, 3% Nitrogênio",
    interestingFacts: "Vênus tem um dia mais longo que seu ano e gira na direção oposta à maioria dos planetas."
  },
  {
    planet: "Terra",
    description: "A Terra é o terceiro planeta a partir do Sol e o único conhecido a abrigar vida. É um mundo oceânico, com 71% de sua superfície coberta por água.",
    diameter: "12742 km",
    mass: "5,97 x 10^24 kg",
    gravity: "9,8 m/s²",
    orbitalPeriod: "365,25 dias",
    rotationPeriod: "24 horas",
    distanceFromSun: "149,6 milhões de km",
    numberOfMoons: 1,
    surfaceTemperature: "14°C (média)",
    atmosphereComposition: "78% Nitrogênio, 21% Oxigênio, 1% Outros Gases",
    interestingFacts: "A Terra é o planeta mais denso do Sistema Solar e o único com água líquida em sua superfície."
  },
  {
    planet: "Marte",
    description: "Marte é o quarto planeta a partir do Sol e é conhecido como o Planeta Vermelho devido à sua aparência avermelhada. Ele possui o maior vulcão e cânion do Sistema Solar.",
    diameter: "6779 km",
    mass: "6,42 x 10^23 kg",
    gravity: "3,71 m/s²",
    orbitalPeriod: "687 dias",
    rotationPeriod: "24,6 horas",
    distanceFromSun: "227,9 milhões de km",
    numberOfMoons: 2,
    surfaceTemperature: "-63°C (média)",
    atmosphereComposition: "95% Dióxido de Carbono, 3% Nitrogênio, 1,6% Argônio",
    interestingFacts: "Marte tem estações como a Terra, mas elas duram cerca de duas vezes mais."
  },
  {
    planet: "Júpiter",
    description: "Júpiter é o quinto planeta a partir do Sol e o maior do Sistema Solar. Ele é um gigante gasoso conhecido por sua Grande Mancha Vermelha, uma enorme tempestade que dura há séculos.",
    diameter: "139820 km",
    mass: "1,90 x 10^27 kg",
    gravity: "24,79 m/s²",
    orbitalPeriod: "11,86 anos",
    rotationPeriod: "9,9 horas",
    distanceFromSun: "778,5 milhões de km",
    numberOfMoons: 79,
    surfaceTemperature: "-108°C",
    atmosphereComposition: "90% Hidrogênio, 10% Hélio",
    interestingFacts: "Júpiter tem o campo magnético mais forte de qualquer planeta e mais de 75 luas, incluindo Ganimedes, a maior lua do Sistema Solar."
  },
  {
    planet: "Saturno",
    description: "Saturno é o sexto planeta a partir do Sol e é famoso por seu deslumbrante sistema de anéis. Ele é um gigante gasoso como Júpiter e tem uma baixa densidade, sendo capaz de flutuar na água.",
    diameter: "116460 km",
    mass: "5,68 x 10^26 kg",
    gravity: "10,44 m/s²",
    orbitalPeriod: "29,5 anos",
    rotationPeriod: "10,7 horas",
    distanceFromSun: "1,43 bilhões de km",
    numberOfMoons: 83,
    surfaceTemperature: "-139°C",
    atmosphereComposition: "96% Hidrogênio, 4% Hélio",
    interestingFacts: "Os anéis de Saturno são feitos principalmente de gelo e rocha e têm apenas cerca de 20 metros de espessura."
  },
  {
    planet: "Urano",
    description: "Urano é o sétimo planeta a partir do Sol e tem uma inclinação única, girando de lado. Ele é um gigante de gelo com uma cor azul-esverdeada devido ao metano em sua atmosfera.",
    diameter: "50724 km",
    mass: "8,68 x 10^25 kg",
    gravity: "8,69 m/s²",
    orbitalPeriod: "84 anos",
    rotationPeriod: "17,2 horas",
    distanceFromSun: "2,87 bilhões de km",
    numberOfMoons: 27,
    surfaceTemperature: "-195°C",
    atmosphereComposition: "82% Hidrogênio, 15% Hélio, 2% Metano",
    interestingFacts: "Urano tem anéis tênues e seu eixo é inclinado em um ângulo de 98 graus, fazendo com que ele gire ao redor do Sol de lado."
  },
  {
    planet: "Netuno",
    description: "Netuno é o oitavo e mais distante planeta conhecido do Sol no Sistema Solar. Ele é um gigante de gelo conhecido por sua cor azul profundo e ventos supersônicos.",
    diameter: "49244 km",
    mass: "1,02 x 10^26 kg",
    gravity: "11,15 m/s²",
    orbitalPeriod: "165 anos",
    rotationPeriod: "16,1 horas",
    distanceFromSun: "4,50 bilhões de km",
    numberOfMoons: 14,
    surfaceTemperature: "-201°C",
    atmosphereComposition: "80% Hidrogênio, 19% Hélio, 1% Metano",
    interestingFacts: "Netuno tem os ventos mais fortes do Sistema Solar, atingindo velocidades de até 2.100 km/h."
  },
  {
    planet: "Plutão",
    description: "Eu era planeta, eu sei, mas isso acabou...",
    diameter: "2377 km",
    mass: "1,31 x 10^22 kg",
    gravity: "0,62 m/s²",
    orbitalPeriod: "248 anos",
    rotationPeriod: "6.387 dias",
    distanceFromSun: "5.913.520.000 km",
    numberOfMoons: 5,
    surfaceTemperature: "-223°C a -233°C",
    atmosphereComposition: "Nitrogênio, Monóxido de carbono, Metano",
    interestingFacts: "Plutão tem uma atmosfera tênue que se congela e sublima à medida que o planeta se afasta e se aproxima do Sol. Seu maior satélite, Caronte, é tão grande em relação a Plutão que os dois são frequentemente considerados um sistema binário."
  }
];
